###
GET http://localhost:8080/order/

###

GET http://localhost:8080/order/7f2c3f0e-ae2d-4967-9885-2832130b0460


###
POST http://localhost:8080/order/
Content-Type: application/json

{
    "items": [{"productId": 1, "quantity": 2}, {"productId": 2, "quantity": 3}],
    "clientId": 777
}
